open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let hdr_init =
    foreign "hdr_init"
      (int64_t @-> int64_t @-> int
      @-> ptr (ptr Types.hdr_histogram)
      @-> returning int)

  let hdr_close =
    foreign "hdr_close" (ptr Types.hdr_histogram @-> returning void)

  let hdr_value_at_percentile =
    foreign "hdr_value_at_percentile"
      (ptr Types.hdr_histogram @-> double @-> returning int64_t)
end
